config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  
  resources :nature, only: [:index]
  resources :landscape, only: [:index]
  resources :family, only: [:index]
  resources :couple, only: [:index]
  resources :portraits, only: [:index]  
  resources :summary, only: [:index]
  resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < MailForm::Base
  
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, validate: true
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "karina.msakata@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request

    if @contact.deliver
      redirect_to new_contact_path, notice: 'Mensagem enviada com sucesso!'
    else
      flash.now.alert = 'Não foi possível enviar a mensagem. Por favor, verifique os erros abaixo.'
      render 'new' 
    end

  end

end

app/controllers/couple_controller.rb
class CoupleController < ApplicationController
  def index
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("couple/*.jpeg")
    end
  end
end

app/controllers/family_controller.rb
class FamilyController < ApplicationController
  def index
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("family/*.jpeg")
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/landscape_controller.rb
class LandscapeController < ApplicationController
  def index
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("landscape/*.jpeg")
    end
  end
end

app/controllers/nature_controller.rb
class NatureController < ApplicationController
  def index
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("nature/*.jpeg")
    end
  end
end

app/controllers/portraits_controller.rb
class PortraitsController < ApplicationController
  def index
    @images = Dir.chdir(Rails.root.join('app/assets/images')) do
      Dir.glob("portraits/*.jpeg")
    end
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController

def index 
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="erro">
  <% if @contact.errors.any? %>
    <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="container-contact">
  <div class="row justify-content-center">
    <div class="col-4">
      <h3>Contato</h3>
      <br>

      <%= form_with(model: @contact) do |f| %>
        <div class="mb-3">
          <%= f.label :name, class:"form-label" %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class:"form-label" %>
          <%= f.text_field :email, class:"form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :message, class:"form-label" %>
          <%= f.text_area :message, class:"form-control" %>
        </div>
        <div class= "d-none">
          <%= f.label :nickname %>
          <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
        </div>
          <%= f.submit 'Enviar', class:"btn btn-primary" %>
      <% end %>
    </div>
    <div class="col-4">
      <div class="contatos">
        <p><%= 'E-mail: karina.msakata@hotmail.com' %></p>
        <p><%= 'Endereço: Sorocaba/SP'%></p>
        <p><%= 'Telefone: (15) 9 8129-6577'%></p>
        <br>
          <%= link_to '<i class="fa-brands fa-instagram"></i>'.html_safe, 'https://www.instagram.com/midorikas' %>
          <%= link_to '<i class="fa-brands fa-linkedin-in"></i>'.html_safe, 'https://www.linkedin.com/in/karinasakata/' %>
          <%= link_to '<i class="fa-brands fa-whatsapp"></i>'.html_safe, 'https://wa.me/5515981296577' %>
      <div>
    </div>
  </div>
</div>

app/views/couple/index.html.erb
<div class="container-lg">
  <div class="gallery"
    <% @images.each do |img| %>
      <%= image_tag img, class:"img", alt:"Couple" %>
    <% end %>
  </div>
</div>

<div class="scroll-container">
  <a><%= link_to '<i class="fa-solid fa-angles-up fa-bounce"></i>'.html_safe, "#top" %></a>
</div>

app/views/family/index.html.erb
<div class="container-lg">
  <div class="gallery">
  <% @images.each do |img| %>
    <div class="photo">
      <%= image_tag img, class:"img", alt:"Family" %>
    </div>
  <% end %>
</div>

<div class="scroll-container">
  <a><%= link_to '<i class="fa-solid fa-angles-up fa-bounce"></i>'.html_safe, "#top" %></a>
</div>

app/views/home/index.html.erb
<div class="container-all">
  <div class="container">
    <%= link_to image_tag("nature/5.jpeg", class:"front-cover"), nature_index_path %>
    <span class="title"><%= 'Natureza' %></span>
  </div>

  <div class="container">
    <%= link_to image_tag("landscape/20.jpeg", class:"front-cover"), landscape_index_path %>
    <span class="title"><%= 'Paisagem' %></span>
  </div>

  <div class="container">
    <%= link_to image_tag("portraits/24.jpeg", class:"front-cover"), portraits_path %>
    <span class="title"><%= 'Retrato/Ensaios' %></span>
  </div>

  <div class="container">
    <%= link_to image_tag("family/24.jpeg", class:"front-cover"), family_index_path %>
    <span class="title"><%= 'Família' %></span>
  </div>

  <div class="container">
    <%= link_to image_tag("couple/39.jpeg", class:"front-cover"), couple_index_path %>
    <span class="title"><%= 'Casais' %></span>
  </div>
</div>
  

app/views/landscape/index.html.erb
<div class="container-lg">
  <div class="gallery">
    <% @images.each do |img| %>
      <%= image_tag img, class:"img", alt:"Landscape" %>
    <% end %>
  </div>
</div>

<div class="scroll-container">
  <a><%= link_to '<i class="fa-solid fa-angles-up fa-bounce"></i>'.html_safe, "#top" %></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Karina Sakata</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('icon.png') %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/80859ebbdd.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "reset" %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_tag 'my_js' %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
    <header class="cabecalho">
    <a>
    <%= link_to (image_tag("logo.png", class: "logo")), root_path %>
    </a>
    <nav>
        <ul class="menu">
          <li><%= link_to 'Vem me conhecer', summary_index_path %></li>
          <li><%= link_to 'Galeria', root_path %></li>
          <li><%= link_to 'Vamos conversar?', new_contact_path %></li>
        </ul>
      </nav>
    </header>
    <div class="alertas">
    <% if !alert.nil? %>
      <div class="alert alert-warning" role="alert">
        <i class="fa-solid fa-triangle-exclamation fa-beat"></i> <%= alert %>
      </div>
    <% end %>

    <% if !notice.nil? %>
      <div class="alert alert-success" role="alert">
        <i class="fa-solid fa-paper-plane fa-beat"></i> <%= notice %>
     </div>
    <% end %>
    </div>

    <%= yield %>

    <footer>
      <div class="criacao">
        <p> Created with <i class="fa-solid fa-heart fa-beat"></i>  by Karina Sakata </p>
      </div>
      <div class="copyright">
        <p> Copyright <i class="fa-regular fa-copyright"></i> 2022 Karina Sakata </p>
      </div>
    </footer>
  </body>
  
  </html>
  

app/views/nature/index.html.erb
<div class="container-lg">
  <div class="gallery">
    <% @images.each do |img| %>
        <%= image_tag img, class:"img", alt:"Natureza" %><onclick="closeFullImg()">
    <% end %>
  </div>
</div>

<div class="scroll-container">
  <a><%= link_to '<i class="fa-solid fa-angles-up fa-bounce"></i>'.html_safe, "#top" %></a>
</div>

app/views/portraits/index.html.erb
<div class="container-lg">
  <div class="gallery">
    <% @images.each do |img| %>
      <%= image_tag img, class:"img", alt:"Portraits" %>
    <% end %>
  </div>
</div>

<div class="scroll-container">
  <a><%= link_to '<i class="fa-solid fa-angles-up fa-bounce"></i>'.html_safe, "#top" %></a>
</div>

app/views/summary/index.html.erb
<main class="perfil">
  <%=image_tag("profile.jpeg", class:"profile") %>
  <div class="descricao">
  <h3>Oi, meu nome é Karina!</h3>
  
  <p>Sou formada em Turismo pela UFSCar Sorocaba e Pós Graduada pela Universidade Anhembi Morumbi em Criação Publicitária e Planejamento de Campanha.

  Atualmente tenho me dedicado para uma transição de carreira para a área de tecnologia, mais precisamente em desenvolvimento web.
  
  Aliado a isso, sou aspirante a fotógrafa. Nas horas vagas e sempre que há uma oportunidade, procuro alguns fazer alguns cliques por aí. 
  
  Quer saber mais sobre mim? Me manda um e-mail, ou me chama pelo whatsapp e a gente conversa melhor!</p>

  </div>
</main>